/*
 * generated by Xtext 2.17.0
 */
package com.zipc.garden.webplatform.dsl.fmc.ide


/**
 * Use this class to register ide components.
 */
class FMCModelIdeModule extends AbstractFMCModelIdeModule {
}
