/**
 *
 * $Id$
 */
package com.zipc.garden.model.arc.validation;

import com.zipc.garden.model.arc.ARCState;

/**
 * A sample validator interface for {@link com.zipc.garden.model.arc.ARCLine}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code
 * generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ARCLineValidator {
    boolean validate();

    boolean validateVariableName(String value);

    boolean validateVariableType(String value);

    boolean validateX(int value);

    boolean validateTarget(ARCState value);

    boolean validateSource(ARCState value);

    boolean validateY(int value);
}
