/**
 *
 * $Id$
 */
package com.zipc.garden.model.arc.validation;

import com.zipc.garden.model.arc.ARCLine;
import com.zipc.garden.model.arc.ARCState;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.arc.ARCRoot}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code
 * generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ARCRootValidator {
    boolean validate();

    boolean validateLines(EList<ARCLine> value);

    boolean validateStates(EList<ARCState> value);

    boolean validateManhattanMode(int value);

}
