/**
 *
 * $Id$
 */
package com.zipc.garden.model.arc.validation;

import com.zipc.garden.model.arc.ARCLine;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.arc.ARCState}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code
 * generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ARCStateValidator {
    boolean validate();

    boolean validateFileId(String value);

    boolean validateName(String value);

    boolean validateIncomingLine(EList<ARCLine> value);

    boolean validateOutgoingLine(EList<ARCLine> value);

    boolean validateEvalPriority(int value);
}
