/**
 *
 * $Id$
 */
package com.zipc.garden.model.scenario.validation;

import com.zipc.garden.model.scenario.Phase;
import com.zipc.garden.model.scenario.PhaseAction;
import com.zipc.garden.model.scenario.PhaseCondition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.scenario.Phase}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PhaseValidator {
    boolean validate();

    boolean validateAction(PhaseAction value);
    boolean validateCondition(PhaseCondition value);
    boolean validateNextPhases(EList<Phase> value);
    boolean validatePrevPhase(Phase value);
    boolean validateName(String value);
}
