/**
 *
 * $Id$
 */
package com.zipc.garden.model.scenario.validation;

import com.zipc.garden.model.scenario.ActorSetting;
import com.zipc.garden.model.scenario.PhaseSetting;
import com.zipc.garden.model.scenario.RoadSetting;

/**
 * A sample validator interface for {@link com.zipc.garden.model.scenario.ScenarioRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ScenarioRootValidator {
    boolean validate();

    boolean validateRoadSetting(RoadSetting value);
    boolean validateActorSetting(ActorSetting value);
    boolean validatePhaseSetting(PhaseSetting value);
}
