/**
 *
 * $Id$
 */
package com.zipc.garden.model.scenario.validation;

import com.zipc.garden.model.scenario.Vehicle;
import com.zipc.garden.model.scenario.VehicleDetailCondition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.scenario.VehicleCondition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VehicleConditionValidator {
    boolean validate();

    boolean validateVehicle(Vehicle value);
    boolean validateConditions(EList<VehicleDetailCondition> value);
}
