/**
 *
 * $Id$
 */
package com.zipc.garden.model.bps.validation;

import com.zipc.garden.model.bps.BPSInstanceStateMachine;
import com.zipc.garden.model.bps.BPSVariable;

/**
 * A sample validator interface for {@link com.zipc.garden.model.bps.BPSDataflow}. This doesn't really do anything, and it's not
 * a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BPSDataflowValidator {
    boolean validate();

    boolean validateSource(BPSInstanceStateMachine value);

    boolean validateTarget(BPSVariable value);
}
