/**
 *
 * $Id$
 */
package com.zipc.garden.model.bps.validation;

import com.zipc.garden.model.bps.BPSDataflow;
import com.zipc.garden.model.bps.BPSInstanceStateMachine;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.bps.BPSInstanceArc}. This doesn't really do anything, and it's
 * not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BPSInstanceArcValidator {
    boolean validate();

    boolean validateOriginalUuid(String value);

    boolean validateOriginalName(String value);

    boolean validateStateMachines(EList<BPSInstanceStateMachine> value);

    boolean validateDataflows(EList<BPSDataflow> value);
}
