/**
 *
 * $Id$
 */
package com.zipc.garden.model.bps.validation;

import com.zipc.garden.model.bps.BPSInstanceState;
import com.zipc.garden.model.bps.BPSVariable;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.bps.BPSInstanceStateMachine}. This doesn't really do anything,
 * and it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate
 * how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BPSInstanceStateMachineValidator {
    boolean validate();

    boolean validateOriginalName(String value);

    boolean validateOriginalUuid(String value);

    boolean validateEvalPriority(int value);

    boolean validateInitialState(BPSInstanceState value);

    boolean validateStates(EList<BPSInstanceState> value);

    boolean validateVariables(EList<BPSVariable> value);
}
