/**
 *
 * $Id$
 */
package com.zipc.garden.model.bps.validation;

import com.zipc.garden.model.bps.BPSInstanceArc;
import com.zipc.garden.model.bps.BPSOption;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.bps.BPSRoot}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code
 * generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BPSRootValidator {
    boolean validate();

    boolean validateOption(EList<BPSOption> value);

    boolean validateActiveOptionIndex(int value);

    boolean validateOptions(EList<BPSOption> value);

    boolean validateInstanceArc(BPSInstanceArc value);

    boolean validateOption(BPSOption value);

    boolean validateTSMFileId(String value);

    boolean validateNSwitch(int value);

}
