/**
 *
 * $Id$
 */
package com.zipc.garden.model.fm.validation;

import com.zipc.garden.model.fm.FMNode;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.fm.FMConstraint}. This doesn't really do anything, and it's not
 * a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FMConstraintValidator {
    boolean validate();

    boolean validateConstraint(String value);

    boolean validateComment(String value);

    boolean validateEnabled(boolean value);

    boolean validateRelatedNodes(EList<FMNode> value);
}
