/**
 *
 * $Id$
 */
package com.zipc.garden.model.fm.validation;

import com.zipc.garden.model.fm.ChildType;
import com.zipc.garden.model.fm.FMNode;
import com.zipc.garden.model.fm.FMProperty;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.fm.FMNode}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code
 * generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FMNodeValidator {
    boolean validate();

    boolean validateChildren(EList<FMNode> value);

    boolean validateTop(int value);

    boolean validateLeft(int value);

    boolean validateHeight(int value);

    boolean validateWidth(int value);

    boolean validateName(String value);

    boolean validateRef(long value);

    boolean validateRefName(String value);

    boolean validateRefInfo(String value);

    boolean validateChildType(ChildType value);

    boolean validateProperties(EList<FMProperty> value);

    boolean validateMin(int value);

    boolean validateMax(int value);

    boolean validateX(int value);

    boolean validateY(int value);

    boolean validateRefuuid(String value);

    boolean validateOptional(boolean value);
}
