/**
 *
 * $Id$
 */
package com.zipc.garden.model.fm.validation;

import com.zipc.garden.model.fm.FMConstraint;
import com.zipc.garden.model.fm.FMNode;
import com.zipc.garden.model.fm.FMProperty;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.fm.FMRoot}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code
 * generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FMRootValidator {
    boolean validate();

    boolean validateNode(FMNode value);

    boolean validateProperties(EList<FMProperty> value);

    boolean validateConstraints(EList<FMConstraint> value);

    boolean validateAutoLayout(int value);

}
