/**
 *
 * $Id$
 */
package com.zipc.garden.model.core.validation;

import com.zipc.garden.model.core.Reference;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.core.AbstractRootElement}. This doesn't really do anything, and
 * it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how
 * EMF's code generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractRootElementValidator {
    boolean validate();

    boolean validateId(String value);

    boolean validateRefs(EList<Reference> value);
}
