/**
 *
 * $Id$
 */
package com.zipc.garden.model.core.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.core.Reference}. This doesn't really do anything, and it's not
 * a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReferenceValidator {
    boolean validate();

    boolean validateRefid(String value);

    boolean validateHash(String value);

    boolean validateRefName(String value);

    boolean validateRefExtension(String value);

    boolean validateRefid(EList<String> value);

    boolean validateHash(EList<String> value);
}
