/**
 *
 * $Id$
 */
package com.zipc.garden.model.scs.validation;

import com.zipc.garden.model.scs.SCSPatternReference;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.scs.SCSPattern}. This doesn't really do anything, and it's not
 * a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SCSPatternValidator {
    boolean validate();

    boolean validateLsc(String value);

    boolean validatePatternreferences(EList<SCSPatternReference> value);

    boolean validateId(String value);

    boolean validatePatternValue(String value);

    boolean validateCscUuid(String value);

    boolean validateCscFileName(String value);

    boolean validateCsc(String value);
}
