/**
 *
 * $Id$
 */
package com.zipc.garden.model.scd.validation;

/**
 * A sample validator interface for {@link com.zipc.garden.model.scd.SCDRoot}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code
 * generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SCDRootValidator {
    boolean validate();

    boolean validateODFileId(long value);

    boolean validateODcFileId(long value);

    boolean validateODDFileId(long value);

    boolean validateBAFileId(long value);

    boolean validateTSDcFileId(long value);

    boolean validateTSDgsFileId(long value);

    boolean validateTSDpFileId(long value);

    boolean validateBgsFileId(long value);

    boolean validateBpFileId(long value);

    boolean validateLSGSFileId(long value);

    boolean validateLSFileId(long value);

    boolean validateCSGSFileId(long value);

    boolean validateCSFileId(long value);

    boolean validateOD(String value);

    boolean validateODC(String value);

    boolean validateBA(String value);

    boolean validateTSDC(String value);

    boolean validateTSDGS(String value);

    boolean validateTSDP(String value);

    boolean validateBGS(String value);

    boolean validateBP(String value);

    boolean validateLSGS(String value);

    boolean validateLS(String value);

    boolean validateCSGS(String value);

    boolean validateCS(String value);

    boolean validateODD(String value);

    boolean validateCSFileName(String value);

    boolean validateTSDCFileName(String value);

    boolean validateBPFileName(String value);

    boolean validateTSDPFileName(String value);

    boolean validateCSGSFileName(String value);

    boolean validateBGSFileName(String value);

    boolean validateTSDGSFileName(String value);

    boolean validateODCFileName(String value);

    boolean validateODFileName(String value);

    boolean validateODDFileName(String value);

    boolean validateBAFileName(String value);

    boolean validateLSFileName(String value);

    boolean validateLSGSFileName(String value);

    boolean validateCBFileId(long value);

    boolean validateSSFileId(long value);

    boolean validateCB(String value);

    boolean validateSS(String value);

    boolean validateCBFileName(String value);

    boolean validateSSFileName(String value);

}
