/*
 * generated by Xtext 2.17.0
 */
package com.zipc.garden.webplatform.dsl.fmc.validation

import com.zipc.garden.webplatform.dsl.fmc.validation.validators.FMCRootValidator
import org.eclipse.xtext.validation.ComposedChecks

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@ComposedChecks(validators=#[
	FMCRootValidator
])
class FMCModelValidator extends AbstractFMCModelValidator {
}
