/**
 *
 * $Id$
 */
package com.zipc.garden.model.bp.validation;

/**
 * A sample validator interface for {@link com.zipc.garden.model.bp.AbstractSetting}. This doesn't really do anything, and it's
 * not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractSettingValidator {
    boolean validate();

    boolean validateUuid(String value);

    boolean validateSettingHash(String value);

    boolean validatePatternNos(String value);

    boolean validateBegin(int value);

    boolean validateEnd(int value);

    boolean validateCount(int value);
}
