/**
 *
 * $Id$
 */
package com.zipc.garden.model.bp.validation;

import com.zipc.garden.model.bp.BPStateMachine;
import com.zipc.garden.model.bp.BPStep;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.bp.BPBehavior}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code
 * generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BPBehaviorValidator {
    boolean validate();

    boolean validateSteps(EList<BPStep> value);

    boolean validateStateMachineRef(BPStateMachine value);
}
