/**
 *
 * $Id$
 */
package com.zipc.garden.model.bp.validation;

import com.zipc.garden.model.bp.BPEvent;
import com.zipc.garden.model.bp.BPSpecElement;
import com.zipc.garden.model.bp.BPState;

/**
 * A sample validator interface for {@link com.zipc.garden.model.bp.BPSpecElement}. This doesn't really do anything, and it's
 * not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BPSpecElementValidator {
    boolean validate();

    boolean validateState(BPState value);

    boolean validateEvent(BPEvent value);

    boolean validateState(BPSpecElement value);

    boolean validateEvent(BPSpecElement value);
}
