/**
 *
 * $Id$
 */
package com.zipc.garden.model.bp.validation;

import com.zipc.garden.model.bp.BPEvent;
import com.zipc.garden.model.bp.BPState;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.bp.BPStateMachine}. This doesn't really do anything, and it's
 * not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BPStateMachineValidator {
    boolean validate();

    boolean validateFsmId(String value);

    boolean validateName(String value);

    boolean validateStates(EList<BPState> value);

    boolean validateEvents(EList<BPEvent> value);
}
