/*
 * generated by Xtext 2.17.0
 */
package com.zipc.garden.webplatform.dsl.sc.validation

import com.zipc.garden.webplatform.dsl.sc.validation.validators.EnvObjectDefValidator
import com.zipc.garden.webplatform.dsl.sc.validation.validators.EnvObjectValidator
import com.zipc.garden.webplatform.dsl.sc.validation.validators.EnvironmentValidator
import com.zipc.garden.webplatform.dsl.sc.validation.validators.LaneValidator
import com.zipc.garden.webplatform.dsl.sc.validation.validators.RangeValidator
import com.zipc.garden.webplatform.dsl.sc.validation.validators.RoadValidator
import com.zipc.garden.webplatform.dsl.sc.validation.validators.RoutesEntityValidator
import com.zipc.garden.webplatform.dsl.sc.validation.validators.RoutesValidator
import com.zipc.garden.webplatform.dsl.sc.validation.validators.SCRootValidator
import org.eclipse.xtext.validation.ComposedChecks

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@ComposedChecks(validators=#[
	SCRootValidator,
	RoadValidator,
	LaneValidator,
	RoutesValidator,
	RoutesEntityValidator,
	EnvironmentValidator,
	RangeValidator,
	EnvObjectValidator,
	EnvObjectDefValidator
])
class SCModelValidator extends AbstractSCModelValidator {
}
