/**
 *
 * $Id$
 */
package com.zipc.garden.webplatform.dsl.core.validation;

import com.zipc.garden.webplatform.dsl.core.IdentifiableElement;
import com.zipc.garden.webplatform.dsl.core.OperatorIdentifier;

/**
 * A sample validator interface for {@link com.zipc.garden.webplatform.dsl.core.AbstractOperation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractOperationValidator {
    boolean validate();

    boolean validateOperator(IdentifiableElement value);

    boolean validateOpIdentifier(OperatorIdentifier value);
}
