/**
 *
 * $Id$
 */
package com.zipc.garden.webplatform.dsl.core.validation;

import com.zipc.garden.webplatform.dsl.core.Expression;

/**
 * A sample validator interface for {@link com.zipc.garden.webplatform.dsl.core.BinaryOperation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BinaryOperationValidator {
    boolean validate();

    boolean validateLeftOperand(Expression value);
    boolean validateRightOperand(Expression value);
}
