/**
 *
 * $Id$
 */
package com.zipc.garden.model.tc.validation;

import com.zipc.garden.model.fm.ChildType;

import com.zipc.garden.model.tc.TCNode;

import com.zipc.garden.model.tc.TCNodeState;
import com.zipc.garden.model.tc.TCProperty;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.tc.TCNode}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code
 * generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TCNodeValidator {
    boolean validate();

    boolean validateName(String value);

    boolean validateChecked(boolean value);

    boolean validateEnabled(boolean value);

    boolean validateChildren(EList<TCNode> value);

    boolean validateChildType(ChildType value);

    boolean validateState(TCNodeState value);

    boolean validateDeleted(boolean value);

    boolean validateInherited(boolean value);

    boolean validateOptional(boolean value);

    boolean validateMin(int value);

    boolean validateMax(int value);

    boolean validateNWiseCombination(int value);

    boolean validateTemporary(boolean value);

    boolean validateProperties(EList<TCProperty> value);

    boolean validateChildType(EList<ChildType> value);

    boolean validateExist(boolean value);
}
