/**
 *
 * $Id$
 */
package com.zipc.garden.model.tps.validation;

import com.zipc.garden.model.fmc.FMCRoot;
import com.zipc.garden.model.tc.TCNode;
import com.zipc.garden.model.tps.NodeVariable;
import com.zipc.garden.model.tps.TPSPatternElement;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.tps.TPSRoot}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code
 * generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TPSRootValidator {
    boolean validate();

    boolean validateNWiseCombination(int value);

    boolean validateRootNodes(EList<TCNode> value);

    boolean validateFmcRoot(FMCRoot value);

    boolean validatePatternElements(EList<TPSPatternElement> value);

    boolean validateNodeVariables(EList<NodeVariable> value);
}
