/*
 * generated by Xtext 2.17.0
 */
package com.zipc.garden.webplatform.dsl.core


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DSLCoreStandaloneSetup extends DSLCoreStandaloneSetupGenerated {

	def static void doSetup() {
		new DSLCoreStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
