/**
 *
 * $Id$
 */
package com.zipc.garden.model.cb.validation;

import com.zipc.garden.model.cb.CBFile;
import com.zipc.garden.model.cb.CBLogic;
import com.zipc.garden.model.cb.CBLogicType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.cb.CBLogic}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code
 * generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CBLogicValidator {
    boolean validate();

    boolean validateChildren(EList<CBLogic> value);

    boolean validateFile(EList<CBFile> value);

    boolean validateType(CBLogicType value);
}
