/**
 *
 * $Id$
 */
package com.zipc.garden.model.csc.validation;

/**
 * A sample validator interface for {@link com.zipc.garden.model.csc.CSCRoot}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code
 * generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CSCRootValidator {
    boolean validate();

    boolean validateAll(double value);

    boolean validateMessage(String value);

    boolean validateEnd(int value);

    boolean validateBegin(int value);

    boolean validateStatus(int value);

}
