/**
 *
 * $Id$
 */
package com.zipc.garden.model.spql.validation;

import com.zipc.garden.model.spql.SPQLSetting;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.spql.SPQLRoot}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code
 * generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SPQLRootValidator {
    boolean validate();

    boolean validateUuid(String value);

    boolean validateFileId(long value);

    boolean validateSettings(EList<SPQLSetting> value);

    boolean validateQuery(String value);

    boolean validateBpFileId(long value);

    boolean validateResult(String value);
}
