/**
 *
 * $Id$
 */
package com.zipc.garden.model.fmcs.validation;

import com.zipc.garden.model.fm.FMNode;

/**
 * A sample validator interface for {@link com.zipc.garden.model.fmcs.FMCSODElement}. This doesn't really do anything, and it's
 * not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FMCSODElementValidator {
    boolean validate();

    boolean validateNode(FMNode value);

    boolean validateFullName(String value);
}
