/**
 *
 * $Id$
 */
package com.zipc.garden.model.fsm.validation;

import com.zipc.garden.model.fsm.FSMDPseudoStateType;
import com.zipc.garden.model.fsm.FSMDRegion;
import com.zipc.garden.model.fsm.FSMDTransition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.fsm.FSMDState}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code
 * generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FSMDStateValidator {
    boolean validate();

    boolean validateRef(long value);

    boolean validateRefName(String value);

    boolean validateName(String value);

    boolean validateEntry(String value);

    boolean validateExit(String value);

    boolean validateDo(String value);

    boolean validateRegions(EList<FSMDRegion> value);

    boolean validateType(FSMDPseudoStateType value);

    boolean validateIncomingTransition(EList<FSMDTransition> value);

    boolean validateOutgoingTransition(EList<FSMDTransition> value);

    boolean validateRefuuid(String value);
}
