/**
 *
 * $Id$
 */
package com.zipc.garden.model.fsm.validation;

import com.zipc.garden.model.fsm.FSMDLine;
import com.zipc.garden.model.fsm.FSMDProperty;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.fsm.FSMDVertex}. This doesn't really do anything, and it's not
 * a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FSMDVertexValidator {
    boolean validate();

    boolean validateTop(int value);

    boolean validateLeft(int value);

    boolean validateHeight(int value);

    boolean validateWidth(int value);

    boolean validateProperties(EList<FSMDProperty> value);

    boolean validateBackground(String value);

    boolean validateForeground(String value);

    boolean validateIncomingLine(EList<FSMDLine> value);

    boolean validateOutgoingLine(FSMDLine value);
}
