/**
 *
 * $Id$
 */
package com.zipc.garden.model.fsm.validation;

import com.zipc.garden.model.fsm.FSMDState;

/**
 * A sample validator interface for {@link com.zipc.garden.model.fsm.FSMDTransition}. This doesn't really do anything, and it's
 * not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FSMDTransitionValidator {
    boolean validate();

    boolean validateTrigger(String value);

    boolean validateEvent(String value);

    boolean validateCondition(String value);

    boolean validateAction(String value);

    boolean validateX(int value);

    boolean validateY(int value);

    boolean validateTarget(FSMDState value);

    boolean validateSource(FSMDState value);

    boolean validatePriority(int value);
}
