/**
 *
 * $Id$
 */
package com.zipc.garden.model.tp.validation;

import com.zipc.garden.model.core.AbstractSetting;
import com.zipc.garden.model.tp.PathType;
import com.zipc.garden.model.tp.TPElement;
import com.zipc.garden.model.tp.TPTSDPattern;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.tp.TPRoot}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code
 * generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TPRootValidator {
    boolean validate();

    boolean validatePatterns(EList<TPTSDPattern> value);

    boolean validateElements(EList<TPElement> value);

    boolean validateAll(double value);

    boolean validateAll(int value);

    boolean validateMessage(String value);

    boolean validateStatus(int value);

    boolean validateEnd(int value);

    boolean validateBegin(int value);

    boolean validateSettings(EList<AbstractSetting> value);

    boolean validateMax(int value);

    boolean validateRowIds(String value);

    boolean validateTitle(PathType value);

    boolean validateHeader(EList<String> value);

    boolean validateDetail(String value);
}
