/**
 *
 * $Id$
 */
package com.zipc.garden.model.tp.validation;

import com.zipc.garden.model.tp.TPElement;

import com.zipc.garden.model.tp.TPPatternElement;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.tp.TPTSDPattern}. This doesn't really do anything, and it's not
 * a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TPTSDPatternValidator {
    boolean validate();

    boolean validateElements(EList<TPElement> value);

    boolean validateId(String value);

    boolean validatePatternElements(EList<TPPatternElement> value);
}
