/**
 *
 * $Id$
 */
package com.zipc.garden.model.fmc.validation;

import com.zipc.garden.model.fmc.FMCConstraint;
import com.zipc.garden.model.fmc.FMCNodePath;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.zipc.garden.model.fmc.FMCRoot}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code
 * generator can be extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FMCRootValidator {
    boolean validate();

    boolean validateConstraints(EList<FMCConstraint> value);

    boolean validateNodepaths(EList<FMCNodePath> value);

    boolean validateDocument(String value);
}
